config/routes.rb
Rails.application.routes.draw do

  # GraphQL API
  unless Rails.env.production?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api/v1/graphql"
  end
  post "/api/v1/graphql", to: "api/v1/graphql#execute"

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        sessions: 'api/v1/sessions',
        registrations: 'api/v1/registrations',
        passwords: 'api/v1/passwords'
      }, skip: [:omniauth_callbacks]
      put 'users/update_avatar' => 'users#update_avatar'
      post 'users/register_phone_number' => 'users#register_phone_number'
      post 'users/verify_phone_number' => 'users#verify_phone_number'
      post 'versions/check_version' => 'versions#check_version'
      post 'auth/refresh_token' => "users#refresh_token"
      post 'users/find_referrer' => 'users#find_referrer'
      patch 'product_lock_histories/:id/upload_unc' => 'product_lock_histories#upload_unc'
      post 'sync/users' => 'sync#users'
      post 'sync/projects' => 'sync#projects'
      post 'sync/products' => 'sync#products'
      post 'sync/deals' => 'sync#deals'
      patch 'users/change_password' => 'users#change_password'
    end
  end

  # CKEditor
  mount Ckeditor::Engine => '/ckeditor'

  # Sidekiq Web
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # ActionCable
  mount ActionCable.server => '/cable'

  # Authenticate user
  devise_for :users, path: 'user',
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               omniauth_callbacks: "users/omniauth_callbacks"
             }

  # authenticated :user do
  #   root to: 'admin/dashboard#index'
  # end
  unauthenticated :user do
    devise_scope :user do
      get '/', to: 'users/sessions#new'
    end
  end

  post '/sync-lead-callio', to: 'sync_lead_callio#sync'

  # Admin Namespace
  namespace :admin, path: '' do
    root to: 'dashboard#index'
    get '/get_access_token', to: 'dashboard#get_access_token'
    resources :dashboard do
      collection do
        post :update_project_selected_ids
        get :get_projects
        get :get_api_dashboard_assignee
        get :get_api_dashboard_deals
        get :get_api_dashboard_commission
        get :unc_product_lock_history
      end
    end
    get '/deals/filter/:type', to: 'deals#filter'
    resources :deals do
      resources :appointments
      resources :calls
      resources :feedbacks
      resources :notes
      resources :online_feedbacks
      resources :history_interactions
      collection do
        get :autocomplete
        get :product_search
        get :product_type_search
        get :project_search
        get :customer_search
        get :assignee_search
        post :reorder
        post :update_commission
        get :get_comm_info
        get :get_all_deal_by_query
        post :update_source_detail
        get :complete_deals
        post :export_deals
      end
      member do
        get :kanban_item
        patch :update_state
        patch :update_assignee
        patch :update_source
        patch :update_create_date
        patch :update_lead_scoring
        post :check_deal_contract_signed_product
        get :new_transfer
        post :create_transfer
      end
      resources :histories, only: :index
    end
    resources :cs_tickets do
      collection do
        get :autocomplete
        get :download_csv
      end
    end
    resources :investors do
      member do
        post :destroy_attachment
      end
      collection do
        get :autocomplete
        get :search
      end
    end
    resources :constructors do
      member do
        post :destroy_attachment
      end
      collection do
        get :autocomplete
        get :search
      end
    end
    resources :operators do
      member do
        post :destroy_attachment
      end
      collection do
        get :autocomplete
        get :search
      end
    end
    resources :developments do
      member do
        post :destroy_attachment
      end
      collection do
        get :autocomplete
        get :search
      end
    end
    resources :projects do
      resources :products do
        collection do
          get :autocomplete
          get :export_template
          post :import
          get :search
          get :state_filter
          get :subdivision_id_filter
          get :block_id_filter
          get :floor_id_filter
          post :get_divisions
        end
        member do
          post :destroy_attachment
          post :update_wish_list
        end
      end
      resources :layouts do
        collection do
          post :get_divisions
        end
      end
      member do
        post :destroy_attachment
        get :show_products
        get :information_for_sellers
        get :lock_rules
        patch :update_lock_rules
        patch :update_sale_policy
        get :product_autocomplete
      end
      collection do
        get :autocomplete
        get :search
        post :import
      end
      resources :custom_details, only: [:index, :create]
      resources :interactive_layouts do
        collection do
          post :get_divisions
          post :find_divisions
        end
      end
      resources :company_revenues, only: [:index, :create, :update, :destroy] do
        collection do
          get :new_exclusive_revenue
          get :new_exception_revenue
        end
      end
      resources :sale_documents, only: [:index, :destroy, :show, :create] do
        member do
          get :download
        end
        collection do
          post :update_media_url
          get :new_investor_post
          post :create_investor_post
          patch '/update_investor_post/:id', to: 'sale_documents#update_investor_post'
          delete '/destroy_investor_post/:id', to: 'sale_documents#destroy_investor_post'
          post :update_sale_kit
          patch '/update_sale_kit', to: 'sale_documents#update_sale_kit'
          post :update_sale_policy
          patch '/update_sale_policy', to: 'sale_documents#update_sale_policy'
          post :create_sale_kit
          post :create_sale_policy
          post :reorder_position
        end
      end
    end
    resources :customers do
      collection do
        get :autocomplete
        post :import
        get :check_same_phone
      end
      member do
        get :vouchers
      end
      resources :customer_journeys do
        collection do
          patch '/', to: 'customer_journeys#update'
          get '/', to: 'customer_journeys#edit'
        end
      end
    end
    resources :regions do
      collection do
        post :get_regions, to: 'regions#get_regions'
      end
    end
    resources :users do
      collection do
        get :export_users
        get :autocomplete
        get :account_autocomplete
        get :search
        get :profile
        patch :update_profile
        post :subscribe
        post :destroy_attachment
      end
    end
    resources :roles do
      member do
        get :new_clone
      end
    end
    resources :deposits do
      collection do
        get :stream_product
        post :finish_countdown
      end
    end
    resources :customer_tickets do
      collection do
        get :autocomplete
      end
    end
    resources :banners do
      member do
        post :destroy_attachment
      end
      collection do
        post :sort
      end
    end
    resources :popups, param: :group
    resources :app_news, only: [:index] do
      collection do
        post :import
      end
    end
    resources :app_banners do
      member do
        post :destroy_attachment
      end
      collection do
        patch '/', to: 'app_banners#update'
      end
    end
    resources :instruction_documents, only: [:index, :create, :destroy]
    resources :custom_htmls, param: :position
    resources :notifications do
      collection do
        get :load_more
        post :read
        get :read_all
      end
    end
    resources :reminders do
      collection do
        get :load_more
        post :read
        get :read_all
      end
    end
    resources :accounts do
      collection do
        get :autocomplete
        get :search
      end
    end
    resources :groups do
      member do
        get :members, to: 'members#index'
        post :add_root_ancestry, to: 'members#add_root_ancestry'
        post :add_child_ancestry, to: 'members#add_child_ancestry'
        post :add_sibling_ancestry, to: 'members#add_sibling_ancestry'
        post :remove_ancestry, to: 'members#remove_ancestry'
      end
      collection do
        get :autocomplete
      end
    end
    # resources :regulations do
    #   collection do
    #     get :autocomplete
    #     post :get_types
    #   end
    # end
    resources :same_deals do
      collection do
        get :autocomplete
      end
    end
    resources :same_customers do
      collection do
        get :autocomplete
      end
    end
    get "/facebook/callback", to: "facebooks#callback"
    resource :facebook
    resources :custom_keywords do
      collection do
        get :projects
      end
    end
    resources :project_new_updates
    resources :kpis do
      collection do
        post :get_teams
      end
    end
    resources :deal_imports
    resources :calendar do
      collection do
        get :get_events
      end
    end
    resources :vouchers do
      collection do
        post :send_voucher
      end
    end
    resources :versions, only: [:index, :update]
    resources :product_lock_histories, only: [:index, :edit, :update]
    resources :campaign_locks do
      collection do
        get :export_template
        put :preview_products
      end
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::BaseController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :set_countries
  before_action :get_source_group, only: [:new, :edit, :create, :update]

  # GET /customers
  # GET /customers.json
  def index
    authorize :customer, :index?
    @customers = policy_scope(Customer)
    query = params[:query].presence || "*"
    @pagy, @customers = pagy_countless(@customers.search_result(query), items: Settings.admin.pagination.customer.per_page)
  end

  def autocomplete
    @customers = policy_scope(Customer)
    render json: @customers.autocomplete_result(params[:query])
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    authorize @customer
    @customer_characteristic = Constant::CUSTOMER_CUSTOMER_CHARACTERISTIC.values_at(*@customer.customer_characteristic)
    @customer_notes = @customer.notes
  end

  # GET /customers/new
  def new
    @cities = RegionData.cities.pluck(:name_with_type, :id)
    @customer = Customer.new
    authorize @customer
    @is_disabled = !policy(@customer).create?
  end

  # GET /customers/1/edit
  def edit
    authorize @customer
    @is_disabled = !policy(@customer).update?
    @cities = RegionData.cities.pluck(:name_with_type, :id)
    @customer_notes = @customer.notes
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    @customer.created_by_id = current_user.id
    if params[:form_id] == 'quick_create'
      @customer.is_mobile = params[:is_mobile] == 'true'
      @customer.data_source = Deal.find_by(id: params[:deal_id])&.source
      authorize @customer
      respond_to do |format|
        @customer_valid = @customer.valid? || (@customer.errors.count == 1 && @customer.errors.include?(:data_source))
        @customer.save(validate: false) if @customer_valid
        format.js { render :new }
      end
      return
    end
    @cities = RegionData.cities.pluck(:name_with_type, :id)
    authorize @customer
    respond_to do |format|
      if @customer.save
        format.html { redirect_to edit_admin_customer_path(@customer.id), notice: 'Khách hàng đã được tạo thành công.' }
        format.json { render :edit, status: :created, location: @customer }
      else
        count_errors
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    authorize @customer
    @cities = RegionData.cities.pluck(:name_with_type, :id)
    respond_to do |format|
      if params[:customer][:deal_id].present?
        @deal = Deal.find(params[:customer][:deal_id])
        if @customer.update(customer_params)
          format.html { redirect_to edit_admin_deal_path(params[:customer][:deal_id]), notice: 'Khách hàng đã được chỉnh sửa thành công.' }
          format.json { render :edit, status: :ok }
        else
          format.js { render :update }
        end
      else
        if @customer.update(customer_params)
          format.html { redirect_to edit_admin_customer_path(@customer.id), notice: 'Khách hàng đã được chỉnh sửa thành công.' }
          format.json { render :edit, status: :ok, location: @customer }
        else
          count_errors
          format.html { render :edit }
          format.json { render json: @customer.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    authorize @customer
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to admin_customers_url, notice: 'Xóa thành công.' }
      format.json { head :no_content }
    end
  end

  def import
    authorize :customer, :import?
    ImportCustomerJob.perform params[:file]&.path, current_user
  end

  def check_same_phone
    phone_number = Phonelib.parse(params[:phone_number], params[:country_code]).full_e164.sub('+', '')
    customer_same = policy_scope(Customer).where.not(id: params[:customer_id].to_i).where(phone_number: phone_number)
    if phone_number.present? && customer_same.present?
      arr = []
      customer_same.each do |cus|
        phone = Phonelib.parse(cus.phone_number, cus.country_code).national&.delete(' ') if cus.phone_number.present? && cus.country_code.present?
        arr.push("<span class='same-customer' data-customer-id=#{cus.id} data-customer-name='#{cus.name}' data-customer-phone='#{phone}'>#{cus.name}</a>")
      end
      msg = "Số điện thoại này đang bị trùng với khách hàng: #{arr.join(', ')}"
      return render json: { status: false, msg: msg }
    end
    return render json: { status: true }
  end

  def vouchers
    @customer = Customer.find(params[:id])
    @vouchers_customers = @customer.vouchers_customers.order(created_at: :desc)
    @pagy, @vouchers_customers = pagy(@vouchers_customers, items: 10)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  def set_countries
    @countries = Phonelib.phone_data.map { |k, v| ["#{ISO3166::Country.new(k).translation('en')} (+#{ISO3166::Country.new(k)&.country_code})", k, { 'data-code': "+#{ISO3166::Country.new(k)&.country_code}" }] if ISO3166::Country.new(k)&.local_name }.compact
  end

  # Only allow a list of trusted parameters through.
  def customer_params
    params.require(:customer).permit(:name, :phone_number, :second_phone_number, :gender, :email, :identity_card, :city_id, :address, :dob,
                                     :data_source, :country_code, { :customer_characteristic => [] }, :facebook_uid, :job, :property_ownership, :nationality, :financial_capability,
                                     :detail, :income, :position, :work_place, :marital_status, notes_attributes: [:id, :created_by_id, :content, :_destroy])
  end

  def get_source_group
    @source_group = Deal.get_source_group
  end

  def count_errors
    @error_count = @customer.errors.messages.except(:"notes.content").count + @customer.notes.map(&:errors).map(&:messages).reject(&:blank?).count
  end
end

app/views/admin/customers/_form.html.haml
.row
  .col
    = form_with model: [:admin, @customer], local: true, class: 'form-customer' do |f|
      %input.d-none#customer_id{value: @customer&.id}
      - unless @is_disabled
        .row.sticky-scroll
          .col
            .card.tms-card
              .card-body
                .float-right
                  %button.btn.btn-reti-secondary.btn_save_has_phone= @customer.new_record? ? 'Lưu' : 'Lưu thay đổi'
      .row.window-content
        .col
          .card
            .card-header.p-0.border-bottom-0
              %ul#custom-content-above-tab.nav.nav-tabs{:role => "tablist"}
                %li.nav-item
                  %a#custom-content-above-home-tab.nav-link.active{"aria-controls" => "custom-content-above-home", "aria-selected" => "true", "data-toggle" => "pill", :href => "#custom-content-above-home", :role => "tab"}
                    %span.badge.badge-danger.tab-highlight{class: @error_count.to_i == 0 ? 'd-none' : '' }
                      = @error_count
                    Thông tin khách hàng
                - unless @customer.new_record?
                  %li.nav-item
                    = link_to 'Hành trình tương tác', admin_customer_customer_journeys_path(@customer), class: 'nav-link'
                  %li.nav-item
                    = link_to 'Voucher đã gửi', vouchers_admin_customer_path(@customer), class: 'nav-link'
            .card-body
              #custom-content-above-tabContent.tab-content
                #custom-content-above-home.tab-pane.fade.show.active{"aria-labelledby" => "customer-vouchers-tab", :role => "tabpanel"}
                  = render "general_information", f: f

app/views/admin/customers/_note_fields.html.haml
.nested-fields
  .row
    .col-11
      .form-group
        .fields
          = f.text_area :content, class: 'form-control', disabled: @is_disabled
          = f.text_field :created_by_id, hidden: true, value: current_user.id
          - f.object.errors.messages[:content].each do |content_error|
            %span.invalid-feedback.custom-validation= content_error
          %span= f.object.author.full_name if (f.object.author.present? && f.object.errors.blank?)
          %span{style: 'font-style: oblique'}= '- Tạo lúc: ' + f.object.created_at.localtime.strftime('%d/%m/%Y %H:%M') if f.object.created_at.present?
    .col-1
      = link_to_remove_association f do
        .form-group
          %button.btn.btn-outline-danger{type: 'button', disabled: @is_disabled}
            %i.fas.fa-trash

app/views/admin/customers/edit.html.haml
- content_for :content_header do
  .col-sm-6
    %h2.m-0.text-dark Chỉnh sửa Khách hàng
  .col-sm-12.mt-2
    %a.main-header--back{href: admin_customers_path}
      %i.fas.fa-chevron-left
        Trở lại danh sách

- content_for :content_body do
  = render 'form'

app/views/admin/customers/index.html.haml
- content_for :content_header do
  .col-sm-10
    %h2.m-0.text-dark Khách Hàng
  .col-2.d-flex.justify-content-end.p-0
    .form-group.mb-1.ml-auto.mr-2
      %a.btn.btn-same-deal{href: admin_same_customers_path}
        Khách hàng trùng

- content_for :content_body do
  .row
    .col
      - if policy(Customer).import?
        .card.tms-card.collapsed-card
          .card-header
            %h3.card-title Import khách hàng
            .card-tools
              %button.btn.btn-tool{type: 'button', data: {card_widget: 'collapse'}}
                %i.fas.fa-plus
          .card-body{style: 'display: none;'}
            = form_with url: import_admin_customers_path, html: {id: "import-project-form", multipart: true}, local: true do |f|
              #files-field-project.dropzone.fallback
              .form-group.input-group.btn-zone
                = f.submit "Import", class: 'btn btn-primary'
  .row
    .col
      .card.tms-card
        .card-body
          = form_with url: admin_customers_path, method: :get, local: true, class: 'input-group search-group' do |f|
            = f.text_field :query, value: params[:query], id: 'customer-search', class: 'form-control typeahead', type: 'search', placeholder: 'Nhập từ khoá tìm kiếm theo: Tên, SĐT'
            %button{type: 'submit'}
              %i.fa.fa-search

  .card
    .card-body
      .table-responsive.p-0
        %table.table.text-nowrap.table-hover.w-100.nowrap.custom-header-product-table.custom-sorting-table.table-nowrap.display
          %thead
            %tr
              %th.border-bottom-none Tên khách hàng
              %th.border-bottom-none Số điện thoại
              %th.border-bottom-none Số điện thoại phụ
              %th.border-bottom-none Giới tính
              %th.border-bottom-none Email
              %th.border-bottom-none CMND
              %th.border-bottom-none Ngày sinh
              %th.border-bottom-none Xác thực
              %th.border-bottom-none.last-col-stick
          %tbody
            - @customers.each do |customer|
              %tr
                %td= customer.name
                %td
                  %div{class: "#{'blank-data' if customer.phone_number_international.blank?}"}= "#{customer.phone_number_international.present? ? customer.phone_number_international : 'Chưa cập nhật'}"
                %td
                  %div{class: "#{'blank-data' if customer.second_phone_number_international.blank?}"}= "#{customer.second_phone_number_international.present? ? customer.second_phone_number_international : 'Chưa cập nhật'}"
                %td
                  %div{class: "#{'blank-data' if customer.get_gender.blank?}"}= "#{customer.get_gender.present? ? customer.get_gender : 'Chưa cập nhật'}"
                %td
                  %div{class: "#{'blank-data' if customer.email.blank?}"}= "#{customer.email.present? ? customer.email : 'Chưa cập nhật'}"
                %td
                  %div{class: "#{'blank-data' if customer.identity_card.blank?}"}= "#{customer.identity_card.present? ? customer.identity_card : 'Chưa cập nhật'}"
                %td
                  %div{class: "#{'blank-data' if customer.get_dob.blank?}"}= "#{customer.get_dob.present? ? customer.get_dob : 'Chưa cập nhật'}"
                %td= customer.get_state
                %td.text-right
                  %a.btn.btn-outline-primary.btn-edit{href: edit_admin_customer_path(customer.id)}
                    %i.fas.fa-pencil-alt
                  - if policy(customer).destroy?
                    %a.btn.btn-outline-primary{href: admin_customer_path(customer.id), data: {method: 'delete', confirm: 'Bạn chắc chắn muốn xóa bản ghi này?'}}
                      %i.fas.fa-trash
      = render partial: 'shared/pagination', locals: { pagy: @pagy }

- content_for :content_footer do
  %footer.main-footer.main-footer-fixed
    .row
      .col-12
        = link_to 'Tạo mới', new_admin_customer_path, class: 'btn btn-primary'

app/views/admin/customers/new.html.haml
- content_for :content_header do
  .col-sm-6
    %h2.m-0.text-dark Thêm Khách hàng
  .col-sm-12.mt-2
    %a.main-header--back{href: admin_customers_path}
      %i.fas.fa-chevron-left
        Trở lại danh sách

- content_for :content_body do
  = render 'form'

app/views/admin/customers/new.js.haml
- if @customer_valid
  :plain
    Swal.fire({
      position: 'center',
      icon: 'success',
      title: "Thêm mới khách hàng \"#{@customer.name}\" thành công!",
      showConfirmButton: false,
      showClass: {
        popup: 'swal-create-customer',
      },
      timer: 3000
    }).then((result) => {
      let $deal_customer = $('#deal_customer');
      $deal_customer.append('<option value="#{j @customer.id.to_s}" data-select2-id="#{j @customer.id.to_s}">#{j @customer.name}</option>');
      $deal_customer.val("#{j @customer.id.to_s}").trigger('change');
      $('#deal_phone_number').val("#{j @customer.phone_number}");
      $deal_customer.closest('.form-group').removeClass('field_with_errors');
      $deal_customer.closest('.form-group').find('.field_with_errors').removeClass('field_with_errors');
      $deal_customer.closest('.form-group').find('.custom-validation').hide();
      if ($deal_customer.closest('#general-info').length > 0) {
        $('#general-info-tab').find('span').text( $('#general-info').find('.row').not(".input-hidden").find('.field_with_errors:not(:has(input[type="hidden"]))').length/2 );
        if ($('#general-info').find('.row').not(".input-hidden").find('.field_with_errors').length == 0) {
          $('#general-info-tab').find('span').addClass('d-none');
        }
      }
    })
- else
  $('#swal2-content').html("#{j render('admin/deals/new_customer')}");

:plain
  $('.tms-select2').select2();

app/views/admin/customers/update.js.haml
$('#edit-deal-customer-modal-body').html("#{j render partial: 'admin/deals/form_edit_deal_customer', locals: {customer: @customer, deal: @deal}}");

app/views/admin/customers/vouchers.html.haml
- content_for :content_header do
  .col-12
    .d-flex
      %span.title-project-detail Voucher đã gửi
- content_for :content_body do
  .card-body.p-0
    .card.mt-3
      .card-header.p-0.border-bottom-0
        %ul#custom-content-above-tab.nav.nav-tabs{:role => "tablist"}
          %li.nav-item
            = link_to 'Thông tin khách hàng', edit_admin_customer_path(@customer), class: 'nav-link'
          - unless @customer.new_record?
            %li.nav-item
              = link_to 'Hành trình tương tác', admin_customer_customer_journeys_path(@customer), class: 'nav-link'
          %li.nav-item
            = link_to 'Voucher đã gửi', vouchers_admin_customer_path(@customer), class: 'nav-link active'
      .card-body{class: "#{'text-center' unless @vouchers_customers.present?}"}
        - unless @vouchers_customers.present?
          %div{style: 'margin: 10% 0'}
            = image_tag 'ticket.svg'
            .ml-2.mr-2.custom-text-color Chưa có voucher nào được gửi đi.
        - else
          .table-responsive.p-0
            %table.table.table-hover.table-nowrap.unable-click{class: "display nowrap", style: "width:100%; color: #434657"}
              %thead
                %tr
                  %th.font-weight-500 Nội dung voucher
                  %th.font-weight-500 ID voucher
                  %th.font-weight-500 Tên giao dịch
                  %th.font-weight-500 Ngày gửi
              %tbody
                - @vouchers_customers.each_with_index do |voucher_customer|
                  %tr
                    %td.text-truncate{style: 'max-width: 450px; white-space: normal !important'}= voucher_customer.voucher&.content
                    %td= voucher_customer.voucher&.id
                    %td{style: 'max-width: 350px;'}
                      %a{href: edit_admin_deal_path(voucher_customer.deal_id), target: '_blank'}= voucher_customer.get_deal_name
                    %td= voucher_customer.created_at.strftime("%d/%m/%Y")
          = render partial: 'shared/pagination', locals: { pagy: @pagy }