config/routes.rb
Rails.application.routes.draw do

  # GraphQL API
  unless Rails.env.production?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api/v1/graphql"
  end
  post "/api/v1/graphql", to: "api/v1/graphql#execute"

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth', controllers: {
        sessions: 'api/v1/sessions',
        registrations: 'api/v1/registrations',
        passwords: 'api/v1/passwords'
      }, skip: [:omniauth_callbacks]
      put 'users/update_avatar' => 'users#update_avatar'
      post 'users/register_phone_number' => 'users#register_phone_number'
      post 'users/verify_phone_number' => 'users#verify_phone_number'
      post 'versions/check_version' => 'versions#check_version'
      post 'auth/refresh_token' => "users#refresh_token"
      post 'users/find_referrer' => 'users#find_referrer'
      patch 'product_lock_histories/:id/upload_unc' => 'product_lock_histories#upload_unc'
      post 'sync/users' => 'sync#users'
      post 'sync/projects' => 'sync#projects'
      post 'sync/products' => 'sync#products'
      post 'sync/deals' => 'sync#deals'
      patch 'users/change_password' => 'users#change_password'
    end
  end

  # CKEditor
  mount Ckeditor::Engine => '/ckeditor'

  # Sidekiq Web
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # ActionCable
  mount ActionCable.server => '/cable'

  # Authenticate user
  devise_for :users, path: 'user',
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               omniauth_callbacks: "users/omniauth_callbacks"
             }

  # authenticated :user do
  #   root to: 'admin/dashboard#index'
  # end
  unauthenticated :user do
    devise_scope :user do
      get '/', to: 'users/sessions#new'
    end
  end

  post '/sync-lead-callio', to: 'sync_lead_callio#sync'

  # Admin Namespace
  namespace :admin, path: '' do
    root to: 'dashboard#index'
    get '/get_access_token', to: 'dashboard#get_access_token'
    resources :dashboard do
      collection do
        post :update_project_selected_ids
        get :get_projects
        get :get_api_dashboard_assignee
        get :get_api_dashboard_deals
        get :get_api_dashboard_commission
        get :unc_product_lock_history
      end
    end
    get '/deals/filter/:type', to: 'deals#filter'
    resources :deals do
      resources :appointments
      resources :calls
      resources :feedbacks
      resources :notes
      resources :online_feedbacks
      resources :history_interactions
      collection do
        get :autocomplete
        get :product_search
        get :product_type_search
        get :project_search
        get :customer_search
        get :assignee_search
        post :reorder
        post :update_commission
        get :get_comm_info
        get :get_all_deal_by_query
        post :update_source_detail
        get :complete_deals
        post :export_deals
      end
      member do
        get :kanban_item
        patch :update_state
        patch :update_assignee
        patch :update_source
        patch :update_create_date
        patch :update_lead_scoring
        post :check_deal_contract_signed_product
        get :new_transfer
        post :create_transfer
      end
      resources :histories, only: :index
    end
    resources :cs_tickets do
      collection do
        get :autocomplete
        get :download_csv
      end
    end
    resources :investors do
      member do
        post :destroy_attachment
      end
      collection do
        get :autocomplete
        get :search
      end
    end
    resources :constructors do
      member do
        post :destroy_attachment
      end
      collection do
        get :autocomplete
        get :search
      end
    end
    resources :operators do
      member do
        post :destroy_attachment
      end
      collection do
        get :autocomplete
        get :search
      end
    end
    resources :developments do
      member do
        post :destroy_attachment
      end
      collection do
        get :autocomplete
        get :search
      end
    end
    resources :projects do
      resources :products do
        collection do
          get :autocomplete
          get :export_template
          post :import
          get :search
          get :state_filter
          get :subdivision_id_filter
          get :block_id_filter
          get :floor_id_filter
          post :get_divisions
        end
        member do
          post :destroy_attachment
          post :update_wish_list
        end
      end
      resources :layouts do
        collection do
          post :get_divisions
        end
      end
      member do
        post :destroy_attachment
        get :show_products
        get :information_for_sellers
        get :lock_rules
        patch :update_lock_rules
        patch :update_sale_policy
        get :product_autocomplete
      end
      collection do
        get :autocomplete
        get :search
        post :import
      end
      resources :custom_details, only: [:index, :create]
      resources :interactive_layouts do
        collection do
          post :get_divisions
          post :find_divisions
        end
      end
      resources :company_revenues, only: [:index, :create, :update, :destroy] do
        collection do
          get :new_exclusive_revenue
          get :new_exception_revenue
        end
      end
      resources :sale_documents, only: [:index, :destroy, :show, :create] do
        member do
          get :download
        end
        collection do
          post :update_media_url
          get :new_investor_post
          post :create_investor_post
          patch '/update_investor_post/:id', to: 'sale_documents#update_investor_post'
          delete '/destroy_investor_post/:id', to: 'sale_documents#destroy_investor_post'
          post :update_sale_kit
          patch '/update_sale_kit', to: 'sale_documents#update_sale_kit'
          post :update_sale_policy
          patch '/update_sale_policy', to: 'sale_documents#update_sale_policy'
          post :create_sale_kit
          post :create_sale_policy
          post :reorder_position
        end
      end
    end
    resources :customers do
      collection do
        get :autocomplete
        post :import
        get :check_same_phone
      end
      member do
        get :vouchers
      end
      resources :customer_journeys do
        collection do
          patch '/', to: 'customer_journeys#update'
          get '/', to: 'customer_journeys#edit'
        end
      end
    end
    resources :regions do
      collection do
        post :get_regions, to: 'regions#get_regions'
      end
    end
    resources :users do
      collection do
        get :export_users
        get :autocomplete
        get :account_autocomplete
        get :search
        get :profile
        patch :update_profile
        post :subscribe
        post :destroy_attachment
      end
    end
    resources :roles do
      member do
        get :new_clone
      end
    end
    resources :deposits do
      collection do
        get :stream_product
        post :finish_countdown
      end
    end
    resources :customer_tickets do
      collection do
        get :autocomplete
      end
    end
    resources :banners do
      member do
        post :destroy_attachment
      end
      collection do
        post :sort
      end
    end
    resources :popups, param: :group
    resources :app_news, only: [:index] do
      collection do
        post :import
      end
    end
    resources :app_banners do
      member do
        post :destroy_attachment
      end
      collection do
        patch '/', to: 'app_banners#update'
      end
    end
    resources :instruction_documents, only: [:index, :create, :destroy]
    resources :custom_htmls, param: :position
    resources :notifications do
      collection do
        get :load_more
        post :read
        get :read_all
      end
    end
    resources :reminders do
      collection do
        get :load_more
        post :read
        get :read_all
      end
    end
    resources :accounts do
      collection do
        get :autocomplete
        get :search
      end
    end
    resources :groups do
      member do
        get :members, to: 'members#index'
        post :add_root_ancestry, to: 'members#add_root_ancestry'
        post :add_child_ancestry, to: 'members#add_child_ancestry'
        post :add_sibling_ancestry, to: 'members#add_sibling_ancestry'
        post :remove_ancestry, to: 'members#remove_ancestry'
      end
      collection do
        get :autocomplete
      end
    end
    # resources :regulations do
    #   collection do
    #     get :autocomplete
    #     post :get_types
    #   end
    # end
    resources :same_deals do
      collection do
        get :autocomplete
      end
    end
    resources :same_customers do
      collection do
        get :autocomplete
      end
    end
    get "/facebook/callback", to: "facebooks#callback"
    resource :facebook
    resources :custom_keywords do
      collection do
        get :projects
      end
    end
    resources :project_new_updates
    resources :kpis do
      collection do
        post :get_teams
      end
    end
    resources :deal_imports
    resources :calendar do
      collection do
        get :get_events
      end
    end
    resources :vouchers do
      collection do
        post :send_voucher
      end
    end
    resources :versions, only: [:index, :update]
    resources :product_lock_histories, only: [:index, :edit, :update]
    resources :campaign_locks do
      collection do
        get :export_template
        put :preview_products
      end
    end
  end
end

app/views/admin/projects/_document_fields.html.haml
.nested-fields
  .card
    .card-body
      .row
        .col-11
          .form-group
            .fields
              = f.label :name, 'Tên'
              = f.text_field :name, class: 'form-control', disabled: @is_disabled
              - f.object.errors.messages[:name].each do |name_error|
                %span.invalid-feedback.custom-validation= name_error
          .form-group
            .fields
              = f.label :description, 'Mô tả'
              = f.text_area :description, class: 'form-control', maxlength: "250", disabled: @is_disabled
              - f.object.errors.messages[:description].each do |description_error|
                %span.invalid-feedback.custom-validation= description_error
              %small.font-italic.text-muted * Tối đa 250 kí tự
          .form-group
            .fields{class: f.object.errors.messages[:file].present? ? "field_with_errors" : ''}
              = f.label :file, 'File'
              .custom-file
                = f.file_field :file, class: 'custom-file-input not_default_error', disabled: @is_disabled, style: 'cursor: pointer'
                = f.hidden_field :file_cache, value: f.object.file_cache
                = f.label :file, "#{f.object&.file&.identifier || 'Chọn file'}", { class: 'custom-file-label form-control not_default_error', style: 'overflow: auto' }
                - f.object.errors.messages[:file].each do |file_error|
                  %span.invalid-feedback.custom-validation= file_error
          .form-group
            .input-file-container-single{'model_name': 'documents', nested_id: f.object.id, column_name: 'preview_image' }
              .fields{class: f.object.errors.messages[:preview_image].present? ? "field_with_errors" : ''}
                = f.label :preview_image, 'Ảnh đại diện'
                .custom-file
                  - if f.object.preview_image.present?
                    = f.hidden_field :preview_image, value: f.object.preview_image.identifier, 'data-url': f.object.preview_image.url, 'data-delete-url': @project.new_record? ? '' : destroy_attachment_admin_project_path(@project), class: 'input-file-item-single'
                  = f.file_field :preview_image, class: 'custom-file-input not_default_error input-file-init-single', disabled: @is_disabled
                  = f.hidden_field :preview_image_cache, value: f.object.preview_image_cache
                  - f.object.errors.messages[:preview_image].each do |preview_image_error|
                    %span.invalid-feedback.custom-validation= preview_image_error
        .col-1
          = link_to_remove_association f do
            .form-group
              %button.btn.btn-outline-danger{type: 'button', style: 'margin-top: 31px', disabled: @is_disabled}
                %i.fas.fa-trash

app/views/admin/projects/_floorplan_image_fields.html.haml
.nested-fields
  .card
    .card-body
      .row
        .col-11
          .form-group
            .fields
              = f.label :real_estate_type  do
                Loại hình BĐS
                %span.required
                  *
              = f.select :real_estate_type, options_for_select(Constant::PROJECT_REAL_ESTATE_TYPE.invert, f.object.real_estate_type), {include_blank: true}, { class: 'tms-select2 form-control floorplan_type', disabled: @is_disabled }
              - f.object.errors.messages[:real_estate_type].each do |real_estate_type_error|
                %span.invalid-feedback.custom-validation= real_estate_type_error
          .form-group
            .input-file-container{'model_name': 'floorplan_images', nested_id: f.object.id, column_name: 'images'}
              %span
                Hình ảnh
              .tms-field-group-body
                - f.object.images.each do |item|
                  = f.hidden_field :images, multiple: true, value: item.identifier, class: 'input-file-item', 'data-url': item.url, 'data-delete-url': @project.new_record? ? '' : destroy_attachment_admin_project_path(@project)
                = f.hidden_field :images_cache
                .row
                  .col.form-group
                    = f.file_field :images, multiple: true, class: 'input-file-init', 'data-browse-on-zone-click': true, 'data-show-upload': false, 'data-show-caption': true, 'data-msg-placeholder': 'Chọn file', disabled: @is_disabled
                    - f.object.errors.messages[:images].each do |item_error|
                      %span.invalid-feedback.custom-validation= item_error
        .col-1
          = link_to_remove_association f do
            .form-group
              %button.btn.btn-outline-danger{type: 'button', style: 'margin-top: 31px', disabled: @is_disabled}
                %i.fas.fa-trash

app/views/admin/projects/_key_value_fields.html.haml
.nested-fields
  .card
    .card-body
      .row
        .col-11
          .form-group
            .fields
              = f.label :title, 'Tiêu đề'
              = f.text_field :title, class: 'form-control', disabled: @is_disabled
              - f.object.errors.messages[:title].each do |title_error|
                %span.invalid-feedback.custom-validation= title_error
          .form-group
            .fields
              = f.label :description, 'Mô tả'
              = f.text_area :description, class: 'form-control', maxlength: "250", disabled: @is_disabled
              - f.object.errors.messages[:description].each do |description_error|
                %span.invalid-feedback.custom-validation= description_error
              %small.font-italic.text-muted * Tối đa 250 kí tự
          .form-group
            .input-file-container-single{'model_name': 'key_values', nested_id: f.object.id, column_name: 'icon' }
              .fields{class: f.object.errors.messages[:icon].present? ? "field_with_errors" : ''}
                = f.label :icon, 'Icon'
                .custom-file
                  - if f.object.icon.present?
                    = f.hidden_field :icon, value: f.object.icon.identifier, 'data-url': f.object.icon.url, 'data-delete-url': @project.new_record? ? '' : destroy_attachment_admin_project_path(@project), class: 'input-file-item-single'
                  = f.file_field :icon, class: 'custom-file-input not_default_error input-file-init-single', disabled: @is_disabled
                  = f.hidden_field :icon_cache, value: f.object.icon_cache
                  - f.object.errors.messages[:icon].each do |icon_error|
                    %span.invalid-feedback.custom-validation= icon_error
        .col-1
          = link_to_remove_association f do
            .form-group
              %button.btn.btn-outline-danger{type: 'button', style: 'margin-top: 31px', disabled: @is_disabled}
                %i.fas.fa-trash

app/views/admin/projects/_legal_document_fields.html.haml
.nested-fields
  .row
    .col-6
      .form-group
        .fields
          = f.label :doc_type do
            Loại tài liệu
            %span.required
              *
          = f.select :doc_type, options_for_select(Constant::PROJECT_LEGAL_DOCUMENTS.invert, f.object.doc_type), {include_blank: true}, class: 'tms-select2 form-control', disabled: @is_disabled
          - f.object.errors.messages[:doc_type].each do |doc_type_error|
            %span.invalid-feedback.custom-validation= doc_type_error
    .col-5
      .form-group
        .fields{class: f.object.errors.messages[:doc].present? ? "field_with_errors" : ''}
          .custom-file{style: 'margin-top: 31px; cursor: pointer'}
            = f.file_field :doc, class: 'custom-file-input not_default_error', disabled: @is_disabled
            = f.hidden_field :doc_cache, value: f.object.doc_cache
            = f.label :doc, "#{f.object&.doc&.identifier || 'Chọn file'}", { class: 'custom-file-label form-control not_default_error', style: 'overflow: auto' }
            - f.object.errors.messages[:doc].each do |doc_error|
              %span.invalid-feedback.custom-validation= doc_error
    .col-1
      = link_to_remove_association f do
        .form-group
          %button.btn.btn-outline-danger{type: 'button', style: 'margin-top: 31px', disabled: @is_disabled}
            %i.fas.fa-trash

app/views/admin/projects/edit.html.haml
- content_for :content_header do
  .col-sm-6
    %h2.m-0.text-dark Chỉnh sửa dự án
  .col-sm-12.mt-2
    %a.main-header--back{href: admin_projects_path}
      %i.fas.fa-chevron-left
        Trở lại danh sách

- content_for :content_body do
  .card.tms-card.shadow-none.w-max-content
    %ul.nav.nav-tabs.bd-bottom-none{role: "tablist", style: 'height: 48px'}
      %li.nav-tab-item
        %a.nav-link.active{"aria-controls" => "project-info", "aria-selected" => "true", "data-toggle" => "pill", role: "tab"} Thông tin chung
      %li.nav-tab-item
        = link_to 'Tuỳ chỉnh chi tiết dự án', admin_project_custom_details_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Bảng hàng', admin_project_products_path(@project, level: 0), class: 'nav-link'
      -#%li.nav-item
      -#  = link_to 'Mặt bằng', admin_project_layouts_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Mặt bằng điện tử', admin_project_interactive_layouts_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Tài liệu bán hàng', admin_project_sale_documents_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Thông tin cho Sale/CTV', information_for_sellers_admin_project_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Cơ chế doanh thu', admin_project_company_revenues_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Quy tắc lock căn', lock_rules_admin_project_path(@project), class: 'nav-link'
  .row 
    .col 
      .card.tms-card
        .card-body
          = render 'form'

app/views/admin/projects/index.html.haml
- content_for :content_header do
  .col-sm-6
    %h2.m-0.text-dark Dự án

- content_for :content_body do
  .row
    .col
      - if policy(Project).import?
        .card.tms-card.collapsed-card
          .card-header
            %h3.card-title Import dự án
            .card-tools
              %button.btn.btn-tool{type: 'button', data: {card_widget: 'collapse'}}
                %i.fas.fa-plus
          .card-body{style: 'display: none;'}
            = form_with url: import_admin_projects_path, html: {id: "import-project-form", multipart: true}, local: true do |f|
              #files-field-project.dropzone.fallback
              .form-group.input-group.btn-zone
                = f.submit "Import", class: 'btn btn-primary'
  .row
    .col
      .card.tms-card
        .card-body
          = form_with url: admin_projects_path, method: :get, local: true, class: 'input-group search-group' do |f|
            = f.text_field :query, value: params[:query], id: 'project-search', class: 'form-control typeahead', type: 'search', placeholder: 'Nhập từ khoá tìm kiếm theo: Tên'
            %button{type: 'submit', id: 'btn-project-search'}
              %i.fa.fa-search
  .card
    .card-body
      .table-responsive.p-0
        %table.table.text-nowrap.table-hover.tms-datatables-scroll.w-100.nowrap.custom-header-product-table.custom-sorting-table.table-nowrap.display
          %thead
            %tr
              %th.first-col-stick{style: 'top: 0 !important'} Hình ảnh
              -#%th.second-col-stick Mã dự án
              %th.second-col-stick{style: 'top: 0 !important'} Tên dự án
              %th.top-0 Loại hình
              %th.top-0 Vị trí
              %th.top-0 Giá từ
              %th.top-0 Giá đến
              %th.top-0 Diện tích nhỏ nhất
              %th.top-0 Diện tích lớn nhất
              %th.top-0 Số hàng còn
              %th.top-0.last-col-stick
          %tbody
            - @projects.each do |project|
              %tr
                %td.first-col-stick= image_tag(project.images.first.url, class: 'img-thumbnail', style: 'width: 100px') if project.images.first.present?
                -#%td.align-middle.second-col-stick= "DA-#{project.id}"
                %td.second-col-stick= project.name
                %td= project.real_estate_type_name.join(', ')
                %td= project.region&.city&.name
                %td
                  %div{class: "#{'blank-data' if project.min_price.blank?}"}= "#{project.min_price.present? ? currency(project.min_price) : 'Chưa cập nhật'}"
                %td
                  %div{class: "#{'blank-data' if project.max_price.blank?}"}= "#{project.max_price.present? ? currency(project.max_price) : 'Chưa cập nhật'}"
                %td
                  %div{class: "#{'blank-data' if project.min_acreage.blank?}"}= "#{project.min_acreage.present? ? acreage(project.min_acreage) : 'Chưa cập nhật'}"
                %td
                  %div{class: "#{'blank-data' if project.max_acreage.blank?}"}= "#{project.max_acreage.present? ? acreage(project.max_acreage) : 'Chưa cập nhật'}"
                %td= project.products.for_sale.size
                %td.text-right.last-col-stick
                  %a.btn.btn-outline-primary.btn-show{href: admin_project_path(project)}
                    %i.far.fa-eye
                  - if policy(project).update?
                    %a.btn.btn-outline-primary.btn-edit{href: edit_admin_project_path(project)}
                      %i.fas.fa-pencil-alt
                  - if policy(project).destroy?
                    %a.btn.btn-outline-primary.remove-project{href: '#', count_deals: project.count_deals, id: project.id}
                      %i.fas.fa-trash

- content_for :content_footer do
  %footer.main-footer.main-footer-fixed
    .row
      .col-12
        = link_to 'Tạo mới', new_admin_project_path, class: 'btn btn-primary'

app/views/admin/projects/information_for_sellers.html.haml
- content_for :content_header do
  .col-sm-6
    %h2.m-0.text-dark Thông tin cho Sale/CTV
  .col-sm-12.mt-2
    %a.main-header--back{href: admin_projects_path}
      %i.fas.fa-chevron-left
        Trở lại danh sách

- content_for :content_body do
  .card.tms-card.shadow-none.w-max-content
    %ul.nav.nav-tabs.bd-bottom-none{role: "tablist", style: 'height: 48px'}
      %li.nav-tab-item
        = link_to 'Thông tin chung', edit_admin_project_path(@project), class: 'nav-link'      
      -#%li.nav-item
      -#  = link_to 'Mặt bằng', admin_project_layouts_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Tuỳ chỉnh chi tiết dự án', admin_project_custom_details_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Bảng hàng', admin_project_products_path(@project, level: 0), class: 'nav-link'  
      %li.nav-tab-item
        = link_to 'Mặt bằng điện tử', admin_project_interactive_layouts_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Tài liệu bán hàng', admin_project_sale_documents_path(@project), class: 'nav-link'      
      %li.nav-tab-item
        %a.nav-link.active{"aria-controls" => "project-info", "aria-selected" => "true", "data-toggle" => "pill", role: "tab"} Thông tin cho Sale/CTV
      %li.nav-tab-item
        = link_to 'Cơ chế doanh thu', admin_project_company_revenues_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Quy tắc lock căn', lock_rules_admin_project_path(@project), class: 'nav-link'
  .row
    .col
      = form_with model: [:admin, @project], url: update_sale_policy_admin_project_path(@project), local: true do |f|
        .row
          .col-12
            .card.tms-card
              .card-body
                .float-right
                  %button.btn.btn-reti-secondary Lưu
        .row
          .col-6
            .card.tms-card
              .card-body
                .form-group
                  = f.label :labels, 'Nhãn dự án'
                  = f.select :labels, options_for_select(@labels.invert, @project.labels), {include_hidden: true}, { class: 'tms-select2 form-control', multiple: true, id: 'project-labels' }
                .form-group
                  = f.label :sale_policy, 'CSBH cho Sale/CTV'
                  = f.text_field :sale_policy, class: 'form-control', placeholder: 'VD: Hoa hồng lên đến 100 triệu'
                .form-group
                  = f.label :description_for_seller, 'Mô tả dự án'
                  = f.text_area :description_for_seller, class: 'form-control'

app/views/admin/projects/lock_rules.html.haml
- content_for :content_header do
  .col-sm-6
    %h2.m-0.text-dark Chỉnh sửa dự án
  .col-sm-12.mt-2
    %a.main-header--back{href: admin_projects_path}
      %i.fas.fa-chevron-left
        Trở lại danh sách

- content_for :content_body do
  .card.tms-card.shadow-none.w-max-content
    %ul.nav.nav-tabs.bd-bottom-none{role: "tablist", style: 'height: 48px'}
      %li.nav-tab-item
        = link_to 'Thông tin chung', edit_admin_project_path(@project), class: 'nav-link'
      -#%li.nav-item
      -#  = link_to 'Mặt bằng', admin_project_layouts_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Tuỳ chỉnh chi tiết dự án', admin_project_custom_details_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Bảng hàng', admin_project_products_path(@project, level: 0), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Mặt bằng điện tử', admin_project_interactive_layouts_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Tài liệu bán hàng', admin_project_sale_documents_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Thông tin cho Sale/CTV', information_for_sellers_admin_project_path(@project), class: 'nav-link'
      %li.nav-tab-item
        = link_to 'Cơ chế doanh thu', admin_project_company_revenues_path(@project), class: 'nav-link'
      %li.nav-tab-item
        %a.nav-link.active{"aria-controls" => "project-info", "aria-selected" => "true", "data-toggle" => "pill", role: "tab"} Quy tắc lock căn
  .row
    .col
      = form_with model: [:admin, @project], url: update_lock_rules_admin_project_path(@project), local: true do |f|
        .card.tms-card
          .row
            .col-6
              .card-body
                .form-group
                  = f.label :queue_lock, 'Số người chờ lock'
                  = f.text_field :queue_lock, class: 'form-control input-queue-lock', type: 'number'
                  - f.object.errors.messages[:queue_lock].each do |queue_lock_error|
                    %span.invalid-feedback.custom-validation= queue_lock_error
                .form-group
                  = f.label :unc_confirmation_period_for_sale, 'Thời gian xác nhận UNC của Sale (phút)'
                  = f.text_field :unc_confirmation_period_for_sale, class: 'form-control input-queue-lock', type: 'number'
                  - f.object.errors.messages[:unc_confirmation_period_for_sale].each do |unc_confirmation_period_for_sale_error|
                    %span.invalid-feedback.custom-validation= unc_confirmation_period_for_sale_error
                .form-group
                  = f.label :unc_confirmation_period_for_sale_admin, 'Thời gian xác nhận UNC của Sale admin (phút)'
                  = f.text_field :unc_confirmation_period_for_sale_admin, class: 'form-control input-queue-lock', type: 'number'
                  - f.object.errors.messages[:unc_confirmation_period_for_sale_admin].each do |unc_confirmation_period_for_sale_admin_error|
                    %span.invalid-feedback.custom-validation= unc_confirmation_period_for_sale_admin_error
                .form-group
                  = f.label :confirm_deposit_by_sale_admin, 'Admin xác nhận cọc'
                  = f.select :confirm_deposit_by_sale_admin, options_for_select(@users, f.object.confirm_deposit_by_sale_admin), {include_hidden: true, include_blank: true}, { class: 'tms-select2 form-control input-queue-lock'}
                %button.btn.btn-tms-unable-submit.btn-save-queue-lock{disabled: true} Lưu thay đổi

app/views/admin/projects/new.html.haml
- content_for :content_header do
  .col-sm-6
    %h2.m-0.text-dark Thêm Dự án
  .col-sm-12.mt-2
    %a.main-header--back{href: admin_projects_path}
      %i.fas.fa-chevron-left
        Trở lại danh sách

- content_for :content_body do
  = render 'form'

app/views/admin/projects/show_products.html.haml
- content_for :content_header do
  .col-12
    .d-flex
      %a{href: admin_project_path(@project), style: 'color: #595959'}
        %i.fas.fa-chevron-left.pt-1.pt-md-2
      %span.title-project-detail Bảng hàng
- content_for :content_body do
  - if browser.device.mobile?
    = render 'admin/projects/mobile/product_table'
  - else
    = render 'product_table'